import type { Metadata } from "next";
import { gaegu, lilita_one } from './fonts'
import Header from "@/components/Header";  
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${lilita_one.variable} ${gaegu.variable}`}>
      <body>
        <Header />
        {children}
        </body>
    </html>
  );
}
